language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli yarn
script:
  - ng build --prod --base-href https://matwjablonski.github.io/bookcase/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/BookcaseApp
  on:
    branch: master
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
